version: "3.7"

x-api: &api_common
  image: "netpicker/api:2.0.4.2--rc"
  environment:
    alembic_version: "6ab16944b8ec"
    LOG_LEVEL: INFO
    UVICORN_ROOT_PATH: /
  volumes:
    - policy-data:/data
  depends_on:
    redis:
      condition: service_healthy
    db:
      condition: service_healthy
    gitd:
      condition: service_started
    gitdctrl:
      condition: service_healthy

services:
  db:
    image: netpicker/db
    container_name: db
    labels:
      netpicker.io: service
    environment:
      POSTGRES_PASSWORD: s3rgts0p!
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  api:
    <<: *api_common
    container_name: api
    labels:
      netpicker.io: service
      service.netpicker.io: api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/status"]
      start_period: 60s
      interval: 5s

  celery:
    <<: *api_common
    container_name: celery
    labels:
      netpicker.io: service
      service.netpicker.io: celery
    command: /run-celery
    healthcheck:
      test: ["CMD", "celery", "inspect", "ping", "-t", "5"]
      start_period: 10s
      interval: 30s

  redis:
    image: redis:7-alpine
    container_name: redis
    labels:
      netpicker.io: service
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  gitd:
    image: "netpicker/gitd:2.0.4.2--rc"
    container_name: gitd
    labels:
      netpicker.io: service
      service.netpicker.io: gitd
    volumes:
      - git:/git

  gitdctrl:
    image: "netpicker/gitdctrl:2.0.4.2--rc"
    container_name: gitdctrl
    labels:
      netpicker.io: service
      service.netpicker.io: gitdctrl
    volumes:
      - git:/git
    healthcheck:
      test: echo "PING" | nc -v localhost 9419
      start_period: 5s
      interval: 5s
    restart: unless-stopped

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    environment:
      SWAGGER_JSON_URL: "/openapi.json"
      TRY_IT_OUT_ENABLED: 1
    depends_on:
      - api

  frontend:
    image: "netpicker/tester-frontend:2.0.4.2--rc"
    container_name: frontend
    labels:
      netpicker.io: service
      service.netpicker.io: front-end
    ports:
      - "80:80"
    depends_on:
      - api

  kibbitzer:
    image: "netpicker/kibbitzer:2.0.4.2--rc"
    container_name: kibbitzer
    labels:
      netpicker.io: service
      service.netpicker.io: kibbitzer
    environment:
      SHENV_API_URL: http://api:8000
      LOG_LEVEL: DEBUG
    healthcheck:
      test: echo "ping Mac\n" | nc -v 127.0.0.1 9696
      start_period: 15s
      interval: 30s
    volumes:
      - secret:/run/secrets
    depends_on:
      - api
      - redis

  agent:
    hostname: agent
    image: "netpicker/agent:2.0.4.2--rc"
    container_name: agent
    labels:
      netpicker.io: service
      service.netpicker.io: agent
    environment:
      CLI_PROXY_ADDR: '0.0.0.0'
      # CLI_TRACE_DIR: /tmp/trace-cli
      # DEDICATED_CONNECTIONS: 1
      # SHENV_JUMP_HOST: '192.168.60.3'
      SHENV_PRIVILEGED_PLATFORMS: 'privileged_platform'
      SHENV_SHOW_RUN_nokia_srl: 'info'
      SHARED_SSH_TTL: 180
    volumes:
      - secret:/run/secrets
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: "echo LST | nc -v 127.0.0.1 8765"
      start_period: 12s
      interval: 10s

  syslog-ng:
    image: "netpicker/syslog-ng:2.0.4.2--rc"
    labels:
      netpicker.io: service
      service.netpicker.io: syslog-ng
    ports:
      - 5514:514/udp
      - 6601:601/tcp
      - 6514:6614/tcp
    volumes:
      - syslog:/var/lib/syslog-ng
    depends_on:
      - agent

volumes:
  config:
  git:
  pg_data:
  policy-data:
  secret:
  syslog:
  transferium:
