x-api: &api_common
  image: "netpicker/api:2.4.0"
  environment:
    alembic_version: "0cc73ffe1fc9"
    CLI_PROXY_HOST: agent
    LOG_LEVEL: INFO
    UVICORN_ROOT_PATH: /
  volumes:
    - policy-data:/data
  depends_on:
    db:
      condition: service_healthy
    gitd:
      condition: service_started
    gitdctrl:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  agent:
    hostname: agent
    image: "netpicker/agent:2.4.0"
    container_name: agent
    labels:
      netpicker.io: service
      service.netpicker.io: agent
    environment:
      CLI_PROXY_ADDR: '0.0.0.0'
      SHARED_SSH_TTL: 180
      NO_PROXY: "api,frontend"
    volumes:
      - secret:/run/secrets
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: "echo LST | nc -v 127.0.0.1 8765"
      start_period: 12s
      interval: 10s

  api:
    <<: *api_common
    container_name: api
    labels:
      netpicker.io: service
      service.netpicker.io: api
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8000/api/v1/status').raise_for_status()"]
      start_period: 60s
      interval: 5s
      retries: 5
      timeout: 10s

  celery:
    <<: *api_common
    depends_on:
      api:
        condition: service_healthy
    container_name: celery
    labels:
      netpicker.io: service
      service.netpicker.io: celery
    command: /run-celery
    healthcheck:
      test: ["CMD-SHELL", "CELERY_BROKER_URL=redis://redis celery inspect ping -t 5"]
      start_period: 15s
      interval: 30s

  db:
    image: netpicker/db
    container_name: db
    labels:
      netpicker.io: service
    environment:
      POSTGRES_PASSWORD: s3rgts0p!
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netpicker"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s


  frontend:
    image: "netpicker/tester-frontend:2.4.0"
    container_name: frontend
    labels:
      netpicker.io: service
      service.netpicker.io: front-end
    ports:
      - "80:80"
    depends_on:
      - api


  gitd:
    image: "netpicker/gitd:2.4.0"
    container_name: gitd
    labels:
      netpicker.io: service
      service.netpicker.io: gitd
    volumes:
      - git:/git


  gitdctrl:
    image: "netpicker/gitdctrl:2.4.0"
    container_name: gitdctrl
    labels:
      netpicker.io: service
      service.netpicker.io: gitdctrl
    volumes:
      - git:/git
    healthcheck:
      test: echo "PING" | nc -v localhost 9419
      start_period: 5s
      interval: 5s
    restart: unless-stopped


  kibbitzer:
    image: "netpicker/kibbitzer:2.4.0"
    container_name: kibbitzer
    labels:
      netpicker.io: service
      service.netpicker.io: kibbitzer
    environment:
      LOG_LEVEL: DEBUG
      SHENV_API_URL: http://api:8000
      SHENV_API_TIMEOUT: 30
      SHENV_PRIVILEGED_PLATFORMS: "gigamon_gigavue arista_eos"
      SHENV_SHOW_RUN_aruba_os: 'show configuration'
      SHENV_SHOW_RUN_corvil: 'show config'
      SHENV_SHOW_RUN_gigamon: 'show running'
      SHENV_SHOW_RUN_meinberg: 'generate_config_backup && cat /var/tmp/lantime_config.backup'
      SHENV_SHOW_RUN_mikrotik_routeros: "export"
      SHENV_SHOW_RUN_nokia_srl: 'info'
      SHENV_SHOW_RUN_paloalto_panos: "show config running"
      SHENV_TAG_SHOW_RUN_mikrotik_routeros_v7: 'export show-sensitive'
    healthcheck:
      test: echo "ping Mac\n" | nc -v 127.0.0.1 9696
      start_period: 15s
      interval: 30s
    volumes:
      - secret:/run/secrets
      - kibbitzer:/celery-worker
      - ./textfsm:/textfsm
    depends_on:
      - api
      - redis

  redis:
    image: redis:7-alpine3.21
    container_name: redis
    labels:
      netpicker.io: service
    volumes:
      - redis:/data
    command: '--save 60 1 --loglevel warning'
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]


  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    environment:
      SWAGGER_JSON_URL: "/openapi.json"
      TRY_IT_OUT_ENABLED: 1
    depends_on:
      - api

  syslog-ng:
    image: "netpicker/syslog-ng:2.4.0"
    container_name: syslog-ng
    labels:
      netpicker.io: service
      service.netpicker.io: syslog-ng
    ports:
      - 5514:514/udp
      - 6601:601/tcp
      - 6514:6614/tcp
    volumes:
      - syslog:/var/lib/syslog-ng
    depends_on:
      - agent

volumes:
  config:
  git:
  kibbitzer:
  pg_data:
  policy-data:
  redis:
  secret:
  syslog:
  transferium:
