.transfer-prompts: &prompts
  "Enter vrf":
    command: ""
    kwargs:
      last_read: 1
  "Destination file":
    command: ""
    kwargs:
      last_read: 1
  "verwrite":
    command: "y"
    kwargs:
      last_read: 1

verify:
  - command: "verify /md5 {dst_file}"
    method: send_command
    kwargs:
      read_timeout: 30
    prompts:
      '= {md5}':
        exc: TransferOK

transfers:
  scp:
    - command: "copy scp://{username}@{src_ip}/{src_file} {dst_file}"
      prompts:
        <<: *prompts
        "re you sure you want to continue": "yes"
        "nter username": "{username}"
        assword:
          command: "{password}"
          method: send_command_progressing
          kwargs:
             expect_string: 'opy complete'
             error_string: 'opy fail'
             #progress_patterns:
             #  percent: (?P<percent>\d+)%
             #  eta: "ETA[: ]+(?P<eta>\\S+)"

errors:
  kibbitzer.exceptions.FileTransferError:
    - No such file or directory
    - Error opening
    - Transfer failed
    - Permission denied
    - "% File not found"
    - "% Invalid"
    - Copy failed
    - No route to host
    - Connection refused
    - Timed out
  kibbitzer.exceptions.InvalidCommand:
    - "^% (.*)"
    - "^ERROR: (.*)"
