{{- if .Values.committer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netpicker.committer.fullname" . }}
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
    app.kubernetes.io/component: committer
    netpicker.io: service
    service.netpicker.io: committer
spec:
  replicas: 1
  {{- with (include "netpicker.sharedVolumeStrategy" .) }}
  {{- . | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netpicker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: committer
  template:
    metadata:
      labels:
        {{- include "netpicker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: committer
        netpicker.io: service
        service.netpicker.io: committer
    spec:
      {{- include "netpicker.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: committer
          image: {{ include "netpicker.image" (dict "global" .Values.global "image" .Values.images.api) }}
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          command: ["/run-celery"]
          env:
            - name: alembic_version
              value: {{ .Values.api.alembicVersion | quote }}
            - name: CLI_PROXY_HOST
              value: {{ .Values.api.cliProxyHost | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.committer.logLevel | quote }}
            - name: UVICORN_ROOT_PATH
              value: {{ .Values.api.uvicornRootPath | quote }}
            - name: CELERY_BROKER_URL
              value: "redis://{{ include "netpicker.redis.fullname" . }}:{{ .Values.redis.service.port }}"
            - name: CELERY_QUEUES
              value: {{ .Values.committer.queues | quote }}
            - name: CELERY_CONCURRENCY
              value: {{ .Values.committer.concurrency | quote }}
            - name: WITHOUT_BEAT
              value: "1"
            - name: GIT_REPO_MANAGER
              value: '["{{ include "netpicker.gitd.fullname" . }}", {{ .Values.gitdctrl.service.port }}]'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretConfig | default "default" }}
                  key: JWT_SECRET
            {{- include "netpicker.s3Env" . | nindent 12 }}
          volumeMounts:
            - name: policy-data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - CELERY_BROKER_URL=redis://{{ include "netpicker.redis.fullname" . }}:{{ .Values.redis.service.port }} celery inspect ping -t 2
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 15
          resources:
            {{- toYaml .Values.committer.resources | nindent 12 }}
      volumes:
        {{- include "netpicker.volume.policyData" . | nindent 8 }}
      securityContext:
        fsGroup: 911
{{- end }}
