{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netpicker.minio.fullname" . }}
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
    netpicker.io: service
    service.netpicker.io: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "netpicker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "netpicker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
        netpicker.io: service
        service.netpicker.io: minio
    spec:
      hostname: minio
      {{- include "netpicker.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: minio
          image: {{ include "netpicker.image" (dict "global" .Values.global "image" .Values.images.minio) }}
          imagePullPolicy: {{ .Values.images.minio.pullPolicy }}
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.root_user | quote }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretConfig | default "default" }}
                  key: MINIO_ROOT_PASSWORD
          ports:
            - name: minio
              containerPort: {{ .Values.minio.service.minio }}
              protocol: TCP
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ include "netpicker.minio.fullname" . }}-data
      securityContext:
        fsGroup: 911
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netpicker.minio.fullname" . }}
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.minio }}
      targetPort: minio
      protocol: TCP
      name: minio
  selector:
    {{- include "netpicker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }}
