{{- if and .Values.testing .Values.testing.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testing.imagePullSecret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\": \"%s\",\"password\": \"%s\",\"auth\": \"%s\"}}}" .Values.testing.imagePullSecret.registry .Values.testing.imagePullSecret.username .Values.testing.imagePullSecret.password (printf "%s:%s" .Values.testing.imagePullSecret.username .Values.testing.imagePullSecret.password | b64enc) | b64enc }}
{{- end }}
