{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.fullname" . }}-config
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
---
{{- end }}

{{- if .Values.persistence.dcVol.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.fullname" . }}-dc-vol
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.dcVol.size }}
---
{{- end }}

{{- if .Values.persistence.transferium.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.fullname" . }}-transferium
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.transferium.size }}
---
{{- end }}



{{- if and .Values.redis.enabled .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.redis.fullname" . }}-data
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
---
{{- end }}

{{- if and .Values.api.enabled .Values.api.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.api.fullname" . }}-data
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size }}
---
{{- end }}

{{- if and .Values.gitd.enabled .Values.gitd.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.gitd.fullname" . }}-data
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gitd.persistence.size }}
---
{{- end }}

{{- if and .Values.kibbitzer.enabled .Values.kibbitzer.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.kibbitzer.fullname" . }}-data
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.kibbitzer.persistence.size }}
---
{{- end }}

{{- if and .Values.agent.enabled .Values.agent.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.agent.fullname" . }}-data
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.agent.persistence.size }}
---
{{- end }}

{{- /* --- Second Agent PVC (agentsecond) --- */}}
{{- if and .Values.agentsecond.enabled .Values.agentsecond.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Use a unique name for the second agent's PVC
  name: {{ include "netpicker.fullname" . }}-agentsecond-data
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
    # Optionally add a component label if needed for selection/management
    # app.kubernetes.io/component: agentsecond
spec:
  accessModes:
    # Use the global access mode or default
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      # Use the size defined in the agentsecond persistence section
      storage: {{ .Values.agentsecond.persistence.size }}
---
{{- end }}

{{- if and .Values.syslogng.enabled .Values.syslogng.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netpicker.syslogng.fullname" . }}-data
  labels:
    {{- include "netpicker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.syslogng.persistence.size }}
{{- end }}
