apiVersion: v1
kind: Secret
metadata:
  name: default
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.postgresPassword | default (randAscii 64) | b64enc | quote }}
  JWT_SECRET: {{ .Values.api.jwtSecret | default (randAscii 64) | b64enc | quote }}
  DB_USER: {{ "netpicker" | b64enc | quote }}
  DB_PASSWORD: {{ "netpicker" | b64enc | quote }}
  DB_ADMIN_USER: {{ "netpicker" | b64enc | quote }}
  DB_ADMIN_PASSWORD: {{ "netpicker" | b64enc | quote }}
