apiVersion: v1
kind: Secret
metadata:
  name: default
type: Opaque
data:
  JWT_SECRET: {{ .Values.api.jwtSecret | default (randAscii 64) | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.postgresPassword | default (randAscii 64) | b64enc }}
  DBPASSWORD: {{ .Values.api.dbPassword  | default (randAscii 64) | b64enc }}