server {
    server_name  0.0.0.0;
    listen 8081;
    listen [::]:8081;

    resolver 127.0.0.11 valid=5s;
    #resolver ${NGINX_RESOLVER} valid=30s;

    proxy_connect_timeout       300;
    proxy_send_timeout          300;
    proxy_read_timeout          300;
    send_timeout                300;

    #access_log  /var/log/nginx/host.access.log  main;

    # reverse proxying for websockets needs a special case
    location /api/v1/agents/ws {
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }

    location /api/ {
        rewrite ^(.*)$ $1 break;
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        # proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /openapi.json {
        rewrite ^(.*)$ $1 break;
        proxy_pass http://api:8000/openapi.json;
    }

    location ~ ^/git/(file-transfers.git|platform-spec.git)/(HEAD|info/refs|objects/info/.*|git-(upload|receive)-pack)$ {
        # This location block handles all access to given git repositories

        # Configure the FastCGI connection to the fcgiwrap socket
        fastcgi_pass unix:/var/run/fcgi/fcgiwrap.socket;
        include fastcgi_params;

        # These parameters are CRUCIAL for git-http-backend
        # 1. PATH_INFO tells fcgiwrap what repository is being accessed
        fastcgi_param PATH_INFO $uri;
        # 2. SCRIPT_FILENAME points to the git CGI binary
        fastcgi_param SCRIPT_FILENAME /usr/libexec/git-core/git-http-backend;
        # 3. GIT_PROJECT_ROOT defines the base directory where git looks for repositories
        fastcgi_param GIT_PROJECT_ROOT /;
        # 4. GIT_HTTP_EXPORT_ALL allows anonymous (unauthenticated) read access
        #fastcgi_param GIT_HTTP_EXPORT_ALL "";

        # Optional: Disable buffering for large Git transfers
        fastcgi_buffering off;
    }

    location ~ ^/git-proxy/(file-transfers.git|platform-spec.git)/(HEAD|info/refs|objects/info/.*|git-(upload|receive)-pack)$ {
	# act as a proxy to dedicated gitd service over http
        rewrite ^\/git-proxy(.*)$ $1 break;
        proxy_pass http://gitd;
    }

    location /swagger/ {
        set $swagger_endpoint http://swagger:8080;
        rewrite ^\/swagger(.*)$ $1 break;
        proxy_pass $swagger_endpoint;
        proxy_intercept_errors on;
        error_page 502 503 504 = @swagger_fallback;
    }

    location @swagger_fallback {
        return 200 "Swagger is currently unavailable, but the rest of the app is fine!";
        add_header Content-Type text/plain;
    }

    # Named location to handle 301 redirects
    location @handle_redirect {
        set $saved_redirect_location $upstream_http_location;
        proxy_pass $saved_redirect_location;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;

        try_files $uri $uri/ /index.html?$args;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
